spring:
  application:
    name: "RagPrototype"
  threads:
    virtual:
      enabled: true
  ai:
    ollama:
      chat:
        options.model: "llama3.1:latest"
      embedding:
        options:
          model: "nomic-embed-text:latest"
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "minioadmin"
          password: "minioadmin"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE
        initialize-schema: true

logging:
  level:
    org:
      springframework:
        ai:
          chat: DEBUG